stages:
  - deploy

deploy:
  image: faircustodian/gitlab-ci-git-push
  stage: deploy
  environment: production
  only:
    - deploy
  script:
    - git-push ssh://git@deis-builder.fcctrl.com:2222/beta.git deploy

staging:
  image: registry.gitlab.com/faircustodian/beta:latest
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - git-push ssh://git@deis-builder.fcctrl.com:2222/staging.git master