stages:
  - deploy

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment: production
  only:
    - deploy
  script:
    - git-push ssh://git@deis-builder.fcctrl.com:2222/beta.git

staging:
  image: ilyasemenov/gitlab-ci-git-push
  stage: staging
  environment: staging
  only:
    - master
  script:
    - git-push ssh://git@deis-builder.fcctrl.com:2222/staging.git