defaults: &defaults
  fog_provider: "AWS"
  aws_access_key_id: "<%= ENV['S3_ACCESS_KEY_ID'] %>"
  aws_secret_access_key: "<%= ENV['S3_SECRET_ACCESS_KEY'] %>"

  # To use AWS reduced redundancy storage.
  # aws_reduced_redundancy: true
  #
  # Change AWS signature version. Default is 4
  # aws_signature_version: 4
  #
  # Change host option in fog (only if you need to)
  # fog_host: "s3.amazonaws.com"
  #
  # Use http instead of https. Default should be "https" (at least for fog-aws)
  # fog_scheme: "http"
  fog_directory: "<%= ENV['FOG_DIRECTORY'] %>"

  # You may need to specify what region your storage bucket is in
  fog_region: "eu-west-1"

  # Set `public` option when uploading file depending on value,
  # Setting to "default" makes asset sync skip setting the option
  # Possible values: true, false, "default" (default: true)
  # config.fog_public = true

  existing_remote_files: keep
  # To delete existing remote files.
  # existing_remote_files: delete

  # Automatically replace files with their equivalent gzip compressed version
  # gzip_compression: true

  # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true

  # Allow custom assets to be cacheable. Note: The base filename will be matched
  # cache_asset_regexps: ['cache_me.js', !ruby/regexp '/cache_some\.\d{8}\.css/']

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults
  enabled: false

staging:
  <<: *defaults
  fog_directory: "faircustodian-staging-assets"

production:
  <<: *defaults
